#!/command/with-contenv bash
set -euo pipefail

LOG_DIR="${LOG_DIR:-/workspace/logs}"
ENV_STATE_FILE="${ENV_STATE_FILE:-/workspace/service_env.sh}"
LITELLM_CONFIG="${LITELLM_CONFIG:-/workspace/litellm.yaml}"

mkdir -p "$LOG_DIR"

# Defaults drawn from env or fallbacks (same semantics as the old start_services.sh)
DEFAULT_JUDGE_MODEL=${JUDGE_MODEL:-Qwen/Qwen3-32B}
DEFAULT_JUDGE_PORT=${JUDGE_PORT:-8000}
DEFAULT_JUDGE_PARALLEL=${JUDGE_PARALLEL:-2}
DEFAULT_DATA_PARALLEL_SIZE=${DATA_PARALLEL_SIZE:-1}
DEFAULT_DATA_PARALLEL_SIZE_LOCAL=${DATA_PARALLEL_SIZE_LOCAL:-$DEFAULT_DATA_PARALLEL_SIZE}
DEFAULT_DATA_PARALLEL_BACKEND=${DATA_PARALLEL_BACKEND:-}
DEFAULT_DATA_PARALLEL_ADDRESS=${DATA_PARALLEL_ADDRESS:-}
DEFAULT_DATA_PARALLEL_RPC_PORT=${DATA_PARALLEL_RPC_PORT:-13345}
DEFAULT_VLLM_MAX_LEN=${VLLM_MAX_MODEL_LEN:-12000}
DEFAULT_VLLM_GPU_UTIL=${VLLM_GPU_MEM_UTIL:-0.90}
DEFAULT_LITELLM_PORT=${LITELLM_PORT:-4000}
DEFAULT_JUDGE_MODEL_NAME=${JUDGE_MODEL_NAME:-judge-local}
DEFAULT_GEN_MODEL_NAME=${GEN_MODEL_NAME:-gen-local}
DEFAULT_ROUTER_MODEL_VALUE=${DEFAULT_ROUTER_MODEL:-$DEFAULT_JUDGE_MODEL_NAME}

# Seed env file if missing (do NOT overwrite if present; change_model.sh owns updates)
if [ ! -f "$ENV_STATE_FILE" ]; then
  cat <<SEED > "$ENV_STATE_FILE"
JUDGE_MODEL=${DEFAULT_JUDGE_MODEL}
GEN_MODEL=${DEFAULT_JUDGE_MODEL}
JUDGE_PORT=${DEFAULT_JUDGE_PORT}
JUDGE_PARALLEL=${DEFAULT_JUDGE_PARALLEL}
DATA_PARALLEL_SIZE=${DEFAULT_DATA_PARALLEL_SIZE}
DATA_PARALLEL_SIZE_LOCAL=${DEFAULT_DATA_PARALLEL_SIZE_LOCAL}
DATA_PARALLEL_BACKEND=${DEFAULT_DATA_PARALLEL_BACKEND}
DATA_PARALLEL_ADDRESS=${DEFAULT_DATA_PARALLEL_ADDRESS}
DATA_PARALLEL_RPC_PORT=${DEFAULT_DATA_PARALLEL_RPC_PORT}
VLLM_MAX_MODEL_LEN=${DEFAULT_VLLM_MAX_LEN}
VLLM_GPU_MEM_UTIL=${DEFAULT_VLLM_GPU_UTIL}
LITELLM_PORT=${DEFAULT_LITELLM_PORT}
JUDGE_MODEL_NAME=${DEFAULT_JUDGE_MODEL_NAME}
GEN_MODEL_NAME=${DEFAULT_GEN_MODEL_NAME}
DEFAULT_ROUTER_MODEL=${DEFAULT_ROUTER_MODEL_VALUE}
SEED
  chmod 600 "$ENV_STATE_FILE"
fi

# Load current values and write LiteLLM config (safe to overwrite each boot)
set -a
source "$ENV_STATE_FILE"
set +a
: "${GEN_MODEL:=$JUDGE_MODEL}"

echo "[cont-init] Seeded $ENV_STATE_FILE"
